import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerOneDirectGroup12GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerOneDirectGroup12Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerOneDirectGroup12Group n b g

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerOneDirectGroup12Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerOneDirectGroup12Group_contains n b g

def computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval where
  signed := computedPhasedBaseFullFiveInnerOneDirectGroup12Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12Signed_contains n b

def computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval where
  bump := computedPhasedBaseFullFiveInnerOneDirectGroup12Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12Bump_contains b n

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0 : RationalInterval :=
  ⟨(1575411879854244931 : ℚ) / 2000000000000000000, (127497883 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1 : RationalInterval :=
  ⟨(4685359937228341 : ℚ) / 12500000000000000, (2800751507 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2 : RationalInterval :=
  ⟨(-70956820241050698943 : ℚ) / 400000000000000000, (49104974963 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3 : RationalInterval :=
  ⟨(-4503102148159852640249 : ℚ) / 2000000000000000000, (10740408868981 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4 : RationalInterval :=
  ⟨(180006873159690645967777 : ℚ) / 2000000000000000000, (469036392957109 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5 : RationalInterval :=
  ⟨(6411223766852465561985857 : ℚ) / 2000000000000000000, (20453292838057119 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6 : RationalInterval :=
  ⟨(-205123512682978389413275293 : ℚ) / 2000000000000000000, (890817821765161747 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7 : RationalInterval :=
  ⟨(-2291526476871957838088192683 : ℚ) / 400000000000000000, (38758890320334708159 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder7,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8 : RationalInterval :=
  ⟨(139772683352147876015936287321 : ℚ) / 1000000000000000000, (210620188527440563763 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder8,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9 : RationalInterval :=
  ⟨(21590930614110415029575900702691 : ℚ) / 2000000000000000000, (73201067075954243350711 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder9,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10 : RationalInterval :=
  ⟨(-364051021663972920235049857085589 : ℚ) / 2000000000000000000, (3178487188932368398607549 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder9, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder10,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11 : RationalInterval :=
  ⟨(-10140762598105304547903729495768509 : ℚ) / 500000000000000000, (34490640919427500388530297 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerOneCompactCell2Shard0PointInterval, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval])

theorem computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11_contains : computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerOneDirectGroup12SignedCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Signed, computedPhasedBaseFullFiveInnerOneDirectGroup12Group, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder9, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder10, computedPhasedBaseFullFiveInnerOneDirectGroup12GroupOrder11,
    computedPhasedBaseFullFiveInnerOneDirectGroup12BumpCache, computedPhasedBaseFullFiveInnerOneDirectGroup12Bump, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder0Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder1Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder2Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder3Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder4Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder5Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder6Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder7Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder8Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder9Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder10Value4, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11Value0, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11Value1, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11Value2, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11Value3, computedPhasedBaseFullFiveInnerOneDirectGroup12BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerOneDirectGroup12Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10,
  computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11
]

def computedPhasedBaseFullFiveInnerOneDirectGroup12Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerOneCompactCell2Shard0Interval.center where
  base := computedPhasedBaseFullFiveInnerOneDirectGroup12Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerOneDirectGroup12BaseOrder11_contains

end
end RiemannVenue.Venue
