import RiemannVenue.Venue.BoundaryComputedPhasedTransformBumpJets9To11

/-!
# Sparse bump-jet numerators 12 through 14

Generated by `scripts/generate_computed_phased_transform_bump_jets.py`.
Every polynomial is checked from the defining recurrence; these are
matrix-transform proof shards, not numerical authority.
-/

namespace RiemannVenue.Venue

open Polynomial

noncomputable def computedTransformBumpJetNumerator12 : ℤ[X] :=
  (100457280 : ℤ[X]) +
      (7125148800 : ℤ[X]) * X ^ 2 +
      ((-22019437440) : ℤ[X]) * X ^ 4 +
      ((-301392241920) : ℤ[X]) * X ^ 6 +
      (1800063587520 : ℤ[X]) * X ^ 8 +
      ((-2436789767808) : ℤ[X]) * X ^ 10 +
      ((-6235266145280) : ℤ[X]) * X ^ 12 +
      (25508066901504 : ℤ[X]) * X ^ 14 +
      ((-31073963300160) : ℤ[X]) * X ^ 16 +
      (1841422619520 : ℤ[X]) * X ^ 18 +
      (33722465546880 : ℤ[X]) * X ^ 20 +
      ((-33389219001600) : ℤ[X]) * X ^ 22 +
      (7967429870400 : ℤ[X]) * X ^ 24 +
      (5796577987200 : ℤ[X]) * X ^ 26 +
      ((-3476234361600) : ℤ[X]) * X ^ 28 +
      (114162048000 : ℤ[X]) * X ^ 30 +
      (171243072000 : ℤ[X]) * X ^ 32 +
      (6227020800 : ℤ[X]) * X ^ 34

theorem explicitStandardBumpJetNumerator_eq_12 :
    explicitStandardBumpJetNumerator 12 =
      computedTransformBumpJetNumerator12 := by
  rw [show 12 = 11 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_11]
  simp [
    computedTransformBumpJetNumerator11,
    computedTransformBumpJetNumerator12,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

noncomputable def computedTransformBumpJetNumerator13 : ℤ[X] :=
  (18871332480 : ℤ[X]) * X ^ 1 +
      (206356550400 : ℤ[X]) * X ^ 3 +
      ((-2972848919040) : ℤ[X]) * X ^ 5 +
      (5122027722240 : ℤ[X]) * X ^ 7 +
      (42292484108160 : ℤ[X]) * X ^ 9 +
      ((-210182271207168) : ℤ[X]) * X ^ 11 +
      (312535092601600 : ℤ[X]) * X ^ 13 +
      (186431372654592 : ℤ[X]) * X ^ 15 +
      ((-1269164153702016) : ℤ[X]) * X ^ 17 +
      (1687230362737920 : ℤ[X]) * X ^ 19 +
      ((-587470703339520) : ℤ[X]) * X ^ 21 +
      ((-819789156426240) : ℤ[X]) * X ^ 23 +
      (1002895861968000 : ℤ[X]) * X ^ 25 +
      ((-323332346937600) : ℤ[X]) * X ^ 27 +
      ((-89337510662400) : ℤ[X]) * X ^ 29 +
      (73406196864000 : ℤ[X]) * X ^ 31 +
      ((-4925573452800) : ℤ[X]) * X ^ 33 +
      ((-2876883609600) : ℤ[X]) * X ^ 35 +
      ((-87178291200) : ℤ[X]) * X ^ 37

theorem explicitStandardBumpJetNumerator_eq_13 :
    explicitStandardBumpJetNumerator 13 =
      computedTransformBumpJetNumerator13 := by
  rw [show 13 = 12 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_12]
  simp [
    computedTransformBumpJetNumerator12,
    computedTransformBumpJetNumerator13,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

noncomputable def computedTransformBumpJetNumerator14 : ℤ[X] :=
  (18871332480 : ℤ[X]) +
      (1524893610240 : ℤ[X]) * X ^ 2 +
      ((-6746994334080) : ℤ[X]) * X ^ 4 +
      ((-93171233675520) : ℤ[X]) * X ^ 6 +
      (704749254168960 : ℤ[X]) * X ^ 8 +
      ((-1189136739318528) : ℤ[X]) * X ^ 10 +
      ((-3640724206630784) : ℤ[X]) * X ^ 12 +
      (18914785931751168 : ℤ[X]) * X ^ 14 +
      ((-30036031771304832) : ℤ[X]) * X ^ 16 +
      (4852789644568320 : ℤ[X]) * X ^ 18 +
      (52330624962295680 : ℤ[X]) * X ^ 20 +
      ((-79233518194871040) : ℤ[X]) * X ^ 22 +
      (40004831727020160 : ℤ[X]) * X ^ 24 +
      (15043912169045760 : ℤ[X]) * X ^ 26 +
      ((-28375646694595200) : ℤ[X]) * X ^ 28 +
      (11073600861523200 : ℤ[X]) * X ^ 30 +
      (1011344458924800 : ℤ[X]) * X ^ 32 +
      ((-1563411885235200) : ℤ[X]) * X ^ 34 +
      (147897971020800 : ℤ[X]) * X ^ 36 +
      (50999300352000 : ℤ[X]) * X ^ 38 +
      (1307674368000 : ℤ[X]) * X ^ 40

theorem explicitStandardBumpJetNumerator_eq_14 :
    explicitStandardBumpJetNumerator 14 =
      computedTransformBumpJetNumerator14 := by
  rw [show 14 = 13 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_13]
  simp [
    computedTransformBumpJetNumerator13,
    computedTransformBumpJetNumerator14,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

end RiemannVenue.Venue
