import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerThreeDirectGroup30GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerThreeDirectGroup30Group n b g

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerThreeDirectGroup30Group_contains n b g

def computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval where
  signed := computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed_contains n b

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval where
  bump := computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump_contains b n

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0 : RationalInterval :=
  ⟨(6908331144663591 : ℚ) / 1000000000000000000, (361 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1 : RationalInterval :=
  ⟨(-151758537588824231 : ℚ) / 1000000000000000000, (36159 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2 : RationalInterval :=
  ⟨(-341652818939495113 : ℚ) / 2000000000000000000, (2187683 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3 : RationalInterval :=
  ⟨(103330312208277011429 : ℚ) / 2000000000000000000, (121941 : ℚ) / 3200000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4 : RationalInterval :=
  ⟨(-698739220133832350133 : ℚ) / 400000000000000000, (2907162101 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5 : RationalInterval :=
  ⟨(-37728747982397369158663 : ℚ) / 500000000000000000, (58206856869 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6 : RationalInterval :=
  ⟨(1650739367989889669844621 : ℚ) / 400000000000000000, (4783222397403 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7 : RationalInterval :=
  ⟨(172736500977469603345528339 : ℚ) / 1000000000000000000, (99540649066697 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder7,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8 : RationalInterval :=
  ⟨(-16196099764841220654200170803 : ℚ) / 2000000000000000000, (1669202939686813 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder8,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9 : RationalInterval :=
  ⟨(-202671892358509242048099347309 : ℚ) / 500000000000000000, (175572236249836097 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder9,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10 : RationalInterval :=
  ⟨(7467833349568908623096050650151 : ℚ) / 500000000000000000, (7406671268014753573 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder10,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11 : RationalInterval :=
  ⟨(1864016770313600416048318743281113 : ℚ) / 2000000000000000000, (625639469553136089187 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup30Group, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup30GroupOrder11,
    computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup30Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder10Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup30BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10,
  computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11
]

def computedPhasedBaseFullFiveInnerThreeDirectGroup30Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerThreeCompactCell5Shard2Interval.center where
  base := computedPhasedBaseFullFiveInnerThreeDirectGroup30Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup30BaseOrder11_contains

end
end RiemannVenue.Venue
