import RiemannVenue.Venue.BoundaryCanonicalBumpPairedTransformPacketCorrection1MinusData

/-!
# Paired canonical-bump packet: Correction1Minus, block 15

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

noncomputable section

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000

theorem canonicalBumpCorrection1MinusPairedBlock15Data_eq :
    canonicalBumpPairedPositiveBlockDataQ
      canonicalBumpCorrection1MinusReal canonicalBumpCorrection1MinusPairedRecurrences
      (15 : Fin 16) =
      { re := (-97018084886466526341359707104025667788719938563188239742511 / 10120111095838037474732720501670543360000000000000000000000000000 : ℚ)
        im := (25855957082949973848539027223323747219448494988009499470667 / 5060055547919018737366360250835271680000000000000000000000000000 : ℚ)
        error := (1380018199033403527490836224967307859967659027319026321400363 / 1727165627023025062354384298951772733440000000000000000000000000000 : ℚ) } := by
  decide +kernel

end

end RiemannVenue.Venue
