import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerFourDirectGroup38GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerFourDirectGroup38Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerFourDirectGroup38Group n b g

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerFourDirectGroup38Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerFourDirectGroup38Group_contains n b g

def computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval where
  signed := computedPhasedBaseFullFiveInnerFourDirectGroup38Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38Signed_contains n b

def computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval where
  bump := computedPhasedBaseFullFiveInnerFourDirectGroup38Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38Bump_contains b n

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0 : RationalInterval :=
  ⟨(891645620108523 : ℚ) / 500000000000000000, (1093 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1 : RationalInterval :=
  ⟨(-12857695097580311 : ℚ) / 2000000000000000000, (40203 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2 : RationalInterval :=
  ⟨(376459905489850727 : ℚ) / 1000000000000000000, (196051 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3 : RationalInterval :=
  ⟨(225271541320601939 : ℚ) / 16000000000000000, (16358059 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4 : RationalInterval :=
  ⟨(-1523978638172317128363 : ℚ) / 2000000000000000000, (365245777 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5 : RationalInterval :=
  ⟨(-22726670402731109093199 : ℚ) / 1000000000000000000, (445291783 : ℚ) / 100000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6 : RationalInterval :=
  ⟨(1652079247609041867066731 : ℚ) / 1000000000000000000, (117028305943 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7 : RationalInterval :=
  ⟨(106492857784650063591703913 : ℚ) / 2000000000000000000, (1358234809843 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder7,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8 : RationalInterval :=
  ⟨(-6857319725658682638852386807 : ℚ) / 2000000000000000000, (207882218298001 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder8,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9 : RationalInterval :=
  ⟨(-25566166295947787441376281407 : ℚ) / 200000000000000000, (173854971892597 : ℚ) / 50000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder9,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10 : RationalInterval :=
  ⟨(13948874871063239578666888779387 : ℚ) / 2000000000000000000, (47176924195735641 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder9, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder10,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11 : RationalInterval :=
  ⟨(3765226333948837311101588407381 : ℚ) / 12500000000000000, (215919260976744521 : ℚ) / 50000000000000000⟩

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerFourCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11_contains : computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerFourDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Signed, computedPhasedBaseFullFiveInnerFourDirectGroup38Group, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder9, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder10, computedPhasedBaseFullFiveInnerFourDirectGroup38GroupOrder11,
    computedPhasedBaseFullFiveInnerFourDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerFourDirectGroup38Bump, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder9Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder10Value4, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11Value0, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11Value1, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11Value2, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11Value3, computedPhasedBaseFullFiveInnerFourDirectGroup38BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerFourDirectGroup38Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10,
  computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11
]

def computedPhasedBaseFullFiveInnerFourDirectGroup38Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerFourCompactCell6Shard12Interval.center where
  base := computedPhasedBaseFullFiveInnerFourDirectGroup38Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerFourDirectGroup38BaseOrder11_contains

end
end RiemannVenue.Venue
