import RiemannVenue.Venue.BoundaryCanonicalBumpTransformPacketCorrection0Plus

/-!
# Staged cached canonical-bump gate: correction 0 plus, cell 0

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

open MeasureTheory Set Polynomial
open scoped BigOperators Interval

noncomputable section

set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

/-- Singleton interval powers stay exact.  This keeps the high-order
bump cache proofs out of sparse `Polynomial.support` reduction. -/
@[simp] theorem canonicalBumpPowSingleton (x : ℚ) (n : ℕ) :
    RationalInterval.pow (RationalInterval.singleton x) n =
      RationalInterval.singleton (x ^ n) := by
  induction n with
  | zero => simp [RationalInterval.pow, RationalInterval.one,
      RationalInterval.singleton]
  | succ n ih =>
      rw [RationalInterval.pow, ih]
      simp [RationalInterval.mul, RationalInterval.singleton, pow_succ]

/-- Sparse polynomial evaluation is exact on singleton intervals. -/
theorem canonicalBumpSparseIntPolynomialSingleton
    (p : ℤ[X]) (x : ℚ) :
    RationalInterval.sparseIntPolynomial p (RationalInterval.singleton x) =
      RationalInterval.singleton
        (Polynomial.eval₂ (Int.castRingHom ℚ) x p) := by
  rw [RationalInterval.sparseIntPolynomial, RationalInterval.sparseSum]
  simp only [canonicalBumpPowSingleton]
  simp [RationalInterval.mul, RationalInterval.singleton,
    Polynomial.eval₂_eq_sum, Polynomial.sum_def]

/-- Record-form companion used after singleton constructors reduce. -/
@[simp] theorem canonicalBumpSparseIntPolynomialZeroRadius
    (p : ℤ[X]) (x : ℚ) :
    RationalInterval.sparseIntPolynomial p ⟨x, 0⟩ =
      ⟨Polynomial.eval₂ (Int.castRingHom ℚ) x p, 0⟩ := by
  simpa [RationalInterval.singleton] using
    canonicalBumpSparseIntPolynomialSingleton p x

/-- Rounded scalar bump jets.  Each entry is validated independently
against the exact point evaluator below. -/
def canonicalBumpCorrection0PlusCell0BumpCache : Fin 12 → RationalInterval := ![
  ⟨0, (3 / 1000000000000 : ℚ)⟩,
  ⟨0, (3 / 1000000000000 : ℚ)⟩,
  ⟨0, (3 / 1000000000000 : ℚ)⟩,
  ⟨0, (3 / 1000000000000 : ℚ)⟩,
  ⟨(1 / 1000000000000 : ℚ), (3 / 1000000000000 : ℚ)⟩,
  ⟨(4479 / 500000000000 : ℚ), (3 / 1000000000000 : ℚ)⟩,
  ⟨(12300893 / 200000000000 : ℚ), (3 / 1000000000000 : ℚ)⟩,
  ⟨(404961177161 / 1000000000000 : ℚ), (1013 / 250000000000 : ℚ)⟩,
  ⟨(2549362842201763 / 1000000000000 : ℚ), (25493631 / 1000000000000 : ℚ)⟩,
  ⟨(7466454360287407 / 488281250 : ℚ), (152912985301 / 1000000000000 : ℚ)⟩,
  ⟨(4249271714583044096 / 48828125 : ℚ), (870250862405399 / 1000000000000 : ℚ)⟩,
  ⟨(114150620678326220488704 / 244140625 : ℚ), (1141506206783262 / 244140625 : ℚ)⟩
]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf0_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 0).Contains
      (canonicalSmoothBump.iterDeriv 0
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 0)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf1_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 1).Contains
      (canonicalSmoothBump.iterDeriv 1
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 1)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf2_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 2).Contains
      (canonicalSmoothBump.iterDeriv 2
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 2)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf3_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 3).Contains
      (canonicalSmoothBump.iterDeriv 3
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 3)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf4_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 4).Contains
      (canonicalSmoothBump.iterDeriv 4
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 4)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf5_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 5).Contains
      (canonicalSmoothBump.iterDeriv 5
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 5)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf6_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 6).Contains
      (canonicalSmoothBump.iterDeriv 6
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 6)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf7_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 7).Contains
      (canonicalSmoothBump.iterDeriv 7
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 7)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf8_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 8).Contains
      (canonicalSmoothBump.iterDeriv 8
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 8)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf9_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 9).Contains
      (canonicalSmoothBump.iterDeriv 9
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 9)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf10_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 10).Contains
      (canonicalSmoothBump.iterDeriv 10
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 10)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpLeaf11_contains :
    (canonicalBumpCorrection0PlusCell0BumpCache 11).Contains
      (canonicalSmoothBump.iterDeriv 11
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := canonicalBumpJetPointIntervalUpTo12_contains
    (expOrder := 32) (split := 16) (n := 11)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num) (by norm_num)
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
    (by
      norm_num [
        canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
        computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
        computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
        explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
        explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
        rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
        RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
        RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
        Finset.sum_range_succ
      ]
    )
  apply RationalInterval.contains_of_center_radius_le hraw
  norm_num [
    canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpPacketMidpoint, canonicalBumpJetPointIntervalUpTo12, computedTransformStableBumpInteriorJetInterval,
    computedTransformHighBumpBoundaryPolynomial, computedTransformBumpBoundaryPolynomial6, computedTransformBumpBoundaryPolynomial7, computedTransformBumpBoundaryPolynomial8,
    computedTransformBumpBoundaryPolynomial9, computedTransformBumpBoundaryPolynomial10, computedTransformBumpBoundaryPolynomial11, computedTransformBumpJetNumeratorUpTo12,
    explicitStandardBumpJetCellInterval, explicitBumpBoundaryJetPolynomialInterval, explicitBumpBoundaryJetCoefficients, RationalInterval.evalPolynomial,
    explicitBumpBoundaryYInterval, explicitBumpGapInterval, RationalInterval.reciprocalPositive, monotoneExpInterval,
    rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor, rationalExpRemainder,
    RationalInterval.ofBounds, RationalInterval.lower, RationalInterval.upper, RationalInterval.scale,
    RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
    RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
    Finset.sum_range_succ
  ]

theorem canonicalBumpCorrection0PlusCell0BumpCache_contains (k : Fin 12) :
    (canonicalBumpCorrection0PlusCell0BumpCache k).Contains
      (canonicalSmoothBump.iterDeriv k
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  fin_cases k
  exact canonicalBumpCorrection0PlusCell0BumpLeaf0_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf1_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf2_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf3_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf4_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf5_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf6_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf7_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf8_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf9_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf10_contains
  exact canonicalBumpCorrection0PlusCell0BumpLeaf11_contains

/-- One rounded exponential kernel shared by all twelve raw jets. -/
def canonicalBumpCorrection0PlusCell0KernelCache : RationalRectangle :=
  ⟨⟨(181478062997 / 250000000000 : ℚ), (1 / 100000000 : ℚ)⟩,
    ⟨(-453850779571 / 200000000000 : ℚ), (1 / 100000000 : ℚ)⟩⟩

theorem canonicalBumpCorrection0PlusCell0KernelCache_contains :
    canonicalBumpCorrection0PlusCell0KernelCache.Contains
      (Complex.exp (Complex.I *
        ((canonicalBumpCorrection0PlusReal : ℝ) +
          (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I) *
        ((canonicalBumpPacketMidpoint 0 : ℝ) : ℂ))) := by
  have hraw := rationalComplexKernelInterval_contains
    (expOrder := 32) (expReduction := 1) (trigOrder := 32)
    (trigHalvings := 4) (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (t := canonicalBumpPacketMidpoint 0) (by norm_num)
    (by simpa [abs_div] using canonicalBumpPacket_kernel_exp 0)
    (by simpa [abs_div] using canonicalBumpCorrection0Plus_kernel_trig 0)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num [
      canonicalBumpCorrection0PlusCell0KernelCache, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, canonicalBumpPacketMidpoint,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]
  · norm_num [
      canonicalBumpCorrection0PlusCell0KernelCache, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, canonicalBumpPacketMidpoint,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]

/-- Compact literal widenings of raw jets computed by the generator
with Lean's exact centered interval algebra. -/
def canonicalBumpCorrection0PlusCell0RawLeaf0 :
    RationalRectangle := ⟨⟨0, (1 / 250000000000 : ℚ)⟩, ⟨0, (1 / 125000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf1 :
    RationalRectangle := ⟨⟨0, (657 / 1000000000000 : ℚ)⟩, ⟨0, (7 / 31250000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf2 :
    RationalRectangle := ⟨⟨0, (4527 / 200000000000 : ℚ)⟩, ⟨0, (63149 / 1000000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf3 :
    RationalRectangle := ⟨⟨0, (1520949 / 250000000000 : ℚ)⟩, ⟨0, (2296369 / 1000000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf4 :
    RationalRectangle := ⟨⟨(1 / 1000000000000 : ℚ), (116172923 / 500000000000 : ℚ)⟩, ⟨(-1 / 500000000000 : ℚ), (586248531 / 1000000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf5 :
    RationalRectangle := ⟨⟨(949 / 125000000000 : ℚ), (28252024673 / 500000000000 : ℚ)⟩, ⟨(-19969 / 1000000000000 : ℚ), (23450307373 / 1000000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf6 :
    RationalRectangle := ⟨⟨(56246833 / 1000000000000 : ℚ), (472294754501 / 200000000000 : ℚ)⟩, ⟨(-16924153 / 125000000000 : ℚ), (5447121949529 / 1000000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf7 :
    RationalRectangle := ⟨⟨(24145686067 / 62500000000 : ℚ), (10504451906551 / 20000000000 : ℚ)⟩, ⟨(-884112916873 / 1000000000000 : ℚ), (118657724809949 / 500000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf8 :
    RationalRectangle := ⟨⟨(2542993354372637 / 1000000000000 : ℚ), (11902094362137883 / 500000000000 : ℚ)⟩, ⟨(-5516706719033211 / 1000000000000 : ℚ), (25326634548028489 / 500000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf9 :
    RationalRectangle := ⟨⟨(7991809240502889981 / 500000000000 : ℚ), (4886054405435918863 / 1000000000000 : ℚ)⟩, ⟨(-32750108223764338511 / 1000000000000 : ℚ), (297949185787621967 / 125000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf10 :
    RationalRectangle := ⟨⟨(95565866075774372590883 / 1000000000000 : ℚ), (238300395899312171379 / 1000000000000 : ℚ)⟩, ⟨(-46032959208351854546667 / 250000000000 : ℚ), (235704323341175098551 / 500000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawLeaf11 :
    RationalRectangle := ⟨⟨(541096075157191264786887601 / 1000000000000 : ℚ), (22750592989922824356011 / 500000000000 : ℚ)⟩, ⟨(-194992604878628255249884161 / 200000000000 : ℚ), (2975747125862382361079 / 125000000000 : ℚ)⟩⟩

def canonicalBumpCorrection0PlusCell0RawCache (k : Fin 12) :
    RationalRectangle :=
  match k.val with
  | 0 => canonicalBumpCorrection0PlusCell0RawLeaf0
  | 1 => canonicalBumpCorrection0PlusCell0RawLeaf1
  | 2 => canonicalBumpCorrection0PlusCell0RawLeaf2
  | 3 => canonicalBumpCorrection0PlusCell0RawLeaf3
  | 4 => canonicalBumpCorrection0PlusCell0RawLeaf4
  | 5 => canonicalBumpCorrection0PlusCell0RawLeaf5
  | 6 => canonicalBumpCorrection0PlusCell0RawLeaf6
  | 7 => canonicalBumpCorrection0PlusCell0RawLeaf7
  | 8 => canonicalBumpCorrection0PlusCell0RawLeaf8
  | 9 => canonicalBumpCorrection0PlusCell0RawLeaf9
  | 10 => canonicalBumpCorrection0PlusCell0RawLeaf10
  | _ => canonicalBumpCorrection0PlusCell0RawLeaf11

theorem canonicalBumpCorrection0PlusCell0RawLeaf0_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf0.Contains
      (iteratedDeriv 0
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 0) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf0, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf0, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf1_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf1.Contains
      (iteratedDeriv 1
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 1) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf1, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf1, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf2_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf2.Contains
      (iteratedDeriv 2
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 2) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf2, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf2, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf3_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf3.Contains
      (iteratedDeriv 3
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 3) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf3, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf3, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf4_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf4.Contains
      (iteratedDeriv 4
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 4) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf4, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf4, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf5_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf5.Contains
      (iteratedDeriv 5
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 5) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf5, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf5, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf6_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf6.Contains
      (iteratedDeriv 6
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 6) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf6, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf6, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf7_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf7.Contains
      (iteratedDeriv 7
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 7) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf7, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf7, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf8_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf8.Contains
      (iteratedDeriv 8
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 8) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf8, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf8, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf9_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf9.Contains
      (iteratedDeriv 9
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 9) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf9, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf9, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf10_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf10.Contains
      (iteratedDeriv 10
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 10) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf10, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf10, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawLeaf11_contains :
    canonicalBumpCorrection0PlusCell0RawLeaf11.Contains
      (iteratedDeriv 11
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  have hraw := rationalTransformRawJetInterval_contains
    (re := canonicalBumpCorrection0PlusReal)
    (im := canonicalBumpPacketImaginaryPart)
    (n := 11) (h := canonicalSmoothBump)
    (t := canonicalBumpPacketMidpoint 0)
    (kernel := canonicalBumpCorrection0PlusCell0KernelCache)
    (testJet := fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache ⟨i, by omega⟩)
    canonicalBumpCorrection0PlusCell0KernelCache_contains
    (fun i =>
      canonicalBumpCorrection0PlusCell0BumpCache_contains ⟨i, by omega⟩)
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf11, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusCell0RawLeaf11, canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpCorrection0PlusCell0BumpCache, canonicalBumpCorrection0PlusCell0KernelCache,
      canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart, rationalTransformRawJetInterval, rationalTransformLambdaQ,
      RationalRectangle.finSum, RationalRectangle.ofRealInterval, RationalRectangle.pow, RationalRectangle.mul,
      RationalRectangle.add, RationalRectangle.one, RationalRectangle.zero, RationalRectangle.singleton,
      RationalInterval.pow, RationalInterval.mul, RationalInterval.sub, RationalInterval.add,
      RationalInterval.neg, RationalInterval.one, RationalInterval.zero, RationalInterval.singleton,
      Nat.choose
    ]

theorem canonicalBumpCorrection0PlusCell0RawCache_contains (k : Fin 12) :
    (canonicalBumpCorrection0PlusCell0RawCache k).Contains
      (iteratedDeriv k
        (computedTransformRawIntegrand canonicalSmoothBump
          ((canonicalBumpCorrection0PlusReal : ℝ) +
            (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
        (canonicalBumpPacketMidpoint 0 : ℝ)) := by
  fin_cases k
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf0_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf1_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf2_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf3_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf4_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf5_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf6_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf7_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf8_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf9_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf10_contains
  simpa [canonicalBumpCorrection0PlusCell0RawCache] using canonicalBumpCorrection0PlusCell0RawLeaf11_contains

noncomputable def canonicalBumpCorrection0PlusCachedCell0 :
    ComplexIntegralCellCertificate
      (computedTransformRawIntegrand canonicalSmoothBump
        ((canonicalBumpCorrection0PlusReal : ℝ) +
          (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
      (equalCellPoint (-1) 1 128 0)
      (equalCellPoint (-1) 1 128 1) :=
  canonicalBumpPacketTransportCell
    (canonicalBumpTaylorCellAtCached
      canonicalBumpCorrection0PlusReal canonicalBumpPacketImaginaryPart
      (canonicalBumpPacketMidpoint 0) canonicalBumpPacketRadius
      canonicalBumpPacket_radius_nonneg canonicalBumpCorrection0PlusReal_bound
      canonicalBumpPacket_imaginary_bound
      canonicalBumpCorrection0PlusCell0RawCache
      canonicalBumpCorrection0PlusCell0RawCache_contains
      (canonicalBumpPacket_window 0))
    (canonicalBumpPacket_left_geometry_real 0)
    (canonicalBumpPacket_right_geometry_real 0)

theorem canonicalBumpCorrection0PlusCachedCell0_center :
    canonicalBumpCorrection0PlusCachedCell0.center =
      ((canonicalBumpCachedCellCenterQ
        canonicalBumpCorrection0PlusCell0RawCache
        canonicalBumpPacketRadius).re.center : ℝ) +
      ((canonicalBumpCachedCellCenterQ
        canonicalBumpCorrection0PlusCell0RawCache
        canonicalBumpPacketRadius).im.center : ℝ) * Complex.I := by
  rw [canonicalBumpCorrection0PlusCachedCell0,
    canonicalBumpPacketTransportCell_center]
  exact canonicalBumpTaylorCellAtCached_center _ _ _ _ _ _ _ _ _ _

theorem canonicalBumpCorrection0PlusCachedCell0_error :
    canonicalBumpCorrection0PlusCachedCell0.error =
      (canonicalBumpCachedCellErrorQ
        canonicalBumpCorrection0PlusCell0RawCache
        canonicalBumpPacketRadius : ℝ) := by
  rw [canonicalBumpCorrection0PlusCachedCell0,
    canonicalBumpPacketTransportCell_error]
  exact canonicalBumpTaylorCellAtCached_error _ _ _ _ _ _ _ _ _ _

theorem canonicalBumpCorrection0PlusCachedCell0_error_lt :
    canonicalBumpCachedCellErrorQ
      canonicalBumpCorrection0PlusCell0RawCache canonicalBumpPacketRadius <
        (3 : ℚ) / 6400000 := by
  norm_num (config := { maxSteps := 1000000 }) [
    canonicalBumpCachedCellErrorQ,
    canonicalBumpCorrection0PlusCell0RawCache, canonicalBumpPacketRadius,
    canonicalBumpCorrection0PlusCell0RawLeaf0, canonicalBumpCorrection0PlusCell0RawLeaf1,
    canonicalBumpCorrection0PlusCell0RawLeaf2, canonicalBumpCorrection0PlusCell0RawLeaf3,
    canonicalBumpCorrection0PlusCell0RawLeaf4, canonicalBumpCorrection0PlusCell0RawLeaf5,
    canonicalBumpCorrection0PlusCell0RawLeaf6, canonicalBumpCorrection0PlusCell0RawLeaf7,
    canonicalBumpCorrection0PlusCell0RawLeaf8, canonicalBumpCorrection0PlusCell0RawLeaf9,
    canonicalBumpCorrection0PlusCell0RawLeaf10, canonicalBumpCorrection0PlusCell0RawLeaf11,
    canonicalBumpOrder12GlobalRawJetBound,
    canonicalBumpRawJetGlobalBound,
    computedTransformBumpGlobalBoundUpTo12, Nat.choose,
    Fin.sum_univ_succ, Finset.sum_range_succ]

end

end RiemannVenue.Venue
