import RiemannVenue.Venue.BoundaryCanonicalBumpPairedTransformPacketCorrection1MinusData

/-!
# Paired canonical-bump packet: Correction1Minus, block 11

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

noncomputable section

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000

theorem canonicalBumpCorrection1MinusPairedBlock11Data_eq :
    canonicalBumpPairedPositiveBlockDataQ
      canonicalBumpCorrection1MinusReal canonicalBumpCorrection1MinusPairedRecurrences
      (11 : Fin 16) =
      { re := (-4838364185142775075025797186915123038114236456080068450274781 / 306670033207213256810082439444561920000000000000000000000000000 : ℚ)
        im := (7668701619555658423064460746595612850609368834053204871747491 / 281114197106612152075908902824181760000000000000000000000000000 : ℚ)
        error := (207009139493163025440288797746436684386817071217680823236547 / 259074844053453759353157644842765910016000000000000000000000000000 : ℚ) } := by
  decide +kernel

end

end RiemannVenue.Venue
