import RiemannVenue.Venue.BoundaryComputedPhasedBumpQuadratureTable

/-! Kernel-checked bump quadrature leaves for jet 2, block 11. Generated by `scripts/generate_computed_phased_bump_quadrature.py`. -/
namespace RiemannVenue.Venue
noncomputable section

set_option maxRecDepth 100000

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_176 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨176, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨176, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨176, by norm_num⟩)).absUpper ≤
      (11871827/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_177 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨177, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨177, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨177, by norm_num⟩)).absUpper ≤
      (11645123/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_178 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨178, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨178, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨178, by norm_num⟩)).absUpper ≤
      (5693509/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_179 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨179, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨179, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨179, by norm_num⟩)).absUpper ≤
      (554761/50000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_180 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨180, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨180, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨180, by norm_num⟩)).absUpper ≤
      (10767293/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_181 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨181, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨181, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨181, by norm_num⟩)).absUpper ≤
      (2080131/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_182 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨182, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨182, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨182, by norm_num⟩)).absUpper ≤
      (2498141/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_183 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨183, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨183, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨183, by norm_num⟩)).absUpper ≤
      (4770059/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_184 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨184, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨184, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨184, by norm_num⟩)).absUpper ≤
      (4520121/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_185 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨185, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨185, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨185, by norm_num⟩)).absUpper ≤
      (4244843/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_186 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨186, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨186, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨186, by norm_num⟩)).absUpper ≤
      (7885017/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_187 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨187, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨187, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨187, by norm_num⟩)).absUpper ≤
      (7222613/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_188 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨188, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨188, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨188, by norm_num⟩)).absUpper ≤
      (6498657/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_189 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨189, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨189, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨189, by norm_num⟩)).absUpper ≤
      (356821/62500 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_190 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨190, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨190, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨190, by norm_num⟩)).absUpper ≤
      (1212459/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_191 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨191, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨191, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨191, by norm_num⟩)).absUpper ≤
      (3916339/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]


end
end RiemannVenue.Venue
