import RiemannVenue.Venue.BoundaryComputedPhasedBumpQuadratureTable

/-! Kernel-checked bump quadrature leaves for jet 0, block 6. Generated by `scripts/generate_computed_phased_bump_quadrature.py`. -/
namespace RiemannVenue.Venue
noncomputable section

set_option maxRecDepth 100000

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_96 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨96, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨96, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨96, by norm_num⟩)).absUpper ≤
      (1647841/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_97 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨97, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨97, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨97, by norm_num⟩)).absUpper ≤
      (1652519/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_98 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨98, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨98, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨98, by norm_num⟩)).absUpper ≤
      (331419/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_99 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨99, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨99, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨99, by norm_num⟩)).absUpper ≤
      (1661567/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_100 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨100, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨100, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨100, by norm_num⟩)).absUpper ≤
      (1665931/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_101 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨101, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨101, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨101, by norm_num⟩)).absUpper ≤
      (208773/125000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_102 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨102, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨102, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨102, by norm_num⟩)).absUpper ≤
      (1674323/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_103 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨103, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨103, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨103, by norm_num⟩)).absUpper ≤
      (839173/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_104 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨104, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨104, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨104, by norm_num⟩)).absUpper ≤
      (210281/125000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_105 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨105, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨105, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨105, by norm_num⟩)).absUpper ≤
      (421507/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_106 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨106, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨106, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨106, by norm_num⟩)).absUpper ≤
      (1689681/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_107 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨107, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨107, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨107, by norm_num⟩)).absUpper ≤
      (338641/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_108 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨108, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨108, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨108, by norm_num⟩)).absUpper ≤
      (424149/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_109 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨109, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨109, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨109, by norm_num⟩)).absUpper ≤
      (33997/20000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_110 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨110, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨110, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨110, by norm_num⟩)).absUpper ≤
      (425741/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_0_111 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      0 (computedPhasedBumpQuadratureCell ⟨111, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨0, by norm_num⟩ ⟨111, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 0
    (computedPhasedBumpQuadratureCell ⟨111, by norm_num⟩)).absUpper ≤
      (341187/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]


end
end RiemannVenue.Venue
