import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerTwoDirectGroup35GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerTwoDirectGroup35Group n b g

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerTwoDirectGroup35Group_contains n b g

def computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval where
  signed := computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed_contains n b

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval where
  bump := computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump_contains b n

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0 : RationalInterval :=
  ⟨(-222211672389098977 : ℚ) / 1000000000000000000, (360567 : ℚ) / 125000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1 : RationalInterval :=
  ⟨(812916159772934163 : ℚ) / 1000000000000000000, (61706993 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2 : RationalInterval :=
  ⟨(145724542329348578027 : ℚ) / 2000000000000000000, (10561557453 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3 : RationalInterval :=
  ⟨(1765191374680565400247 : ℚ) / 2000000000000000000, (451948414501 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4 : RationalInterval :=
  ⟨(-39510246193281385163203 : ℚ) / 1000000000000000000, (9670375637727 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5 : RationalInterval :=
  ⟨(-2662767893837777880856623 : ℚ) / 2000000000000000000, (827722491549179 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6 : RationalInterval :=
  ⟨(92328748564474248512018731 : ℚ) / 2000000000000000000, (1417059346019699 : ℚ) / 80000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7 : RationalInterval :=
  ⟨(1009116896859947864666626859 : ℚ) / 400000000000000000, (1516386148493650313 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder7,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8 : RationalInterval :=
  ⟨(-121324340662486193724001859677 : ℚ) / 2000000000000000000, (64913745903719624601 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder8,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9 : RationalInterval :=
  ⟨(-399498344001940822415618673567 : ℚ) / 80000000000000000, (555835320247122986083 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder9,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10 : RationalInterval :=
  ⟨(17455197879508626381239683272933 : ℚ) / 250000000000000000, (2975060029609364729769 : ℚ) / 50000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder10,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11 : RationalInterval :=
  ⟨(482578460213003094743045920913181 : ℚ) / 50000000000000000, (1274100535820861572273997 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup35Group, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup35GroupOrder11,
    computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup35Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder10Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup35BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10,
  computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11
]

def computedPhasedBaseFullFiveInnerTwoDirectGroup35Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerTwoCompactCell5Shard28Interval.center where
  base := computedPhasedBaseFullFiveInnerTwoDirectGroup35Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup35BaseOrder11_contains

end
end RiemannVenue.Venue
