import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerTwoDirectGroup0GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerTwoDirectGroup0Group n b g

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerTwoDirectGroup0Group_contains n b g

def computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval where
  signed := computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed_contains n b

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval where
  bump := computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump_contains b n

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0 : RationalInterval :=
  ⟨(-22050934171633247 : ℚ) / 2000000000000000000, (16163 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1 : RationalInterval :=
  ⟨(-42802356603802719 : ℚ) / 2000000000000000000, (634843 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2 : RationalInterval :=
  ⟨(8610398314148448731 : ℚ) / 2000000000000000000, (5200453 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3 : RationalInterval :=
  ⟨(67126171276520179473 : ℚ) / 2000000000000000000, (1084171261 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4 : RationalInterval :=
  ⟨(-501490229000693904247 : ℚ) / 125000000000000000, (4558655581 : ℚ) / 200000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5 : RationalInterval :=
  ⟨(-78260700217893591876413 : ℚ) / 1000000000000000000, (480992225797 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6 : RationalInterval :=
  ⟨(14518329998321989619707459 : ℚ) / 2000000000000000000, (650982265059 : ℚ) / 16000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7 : RationalInterval :=
  ⟨(52787517123656681146144833 : ℚ) / 250000000000000000, (430664419405413 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder7,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8 : RationalInterval :=
  ⟨(-2843872146983324321345501101 : ℚ) / 200000000000000000, (72996854891833449 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder8,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9 : RationalInterval :=
  ⟨(-224375806746893140176549742689 : ℚ) / 400000000000000000, (6189544569911099453 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder9,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10 : RationalInterval :=
  ⟨(52048714730649937721765463109039 : ℚ) / 2000000000000000000, (262539590752580353827 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder10,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11 : RationalInterval :=
  ⟨(2748626231974051302957088793262337 : ℚ) / 2000000000000000000, (11139927437296083757933 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup0Group, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup0GroupOrder11,
    computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup0Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder10Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup0BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10,
  computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11
]

def computedPhasedBaseFullFiveInnerTwoDirectGroup0Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerTwoCompactCell0Shard0Interval.center where
  base := computedPhasedBaseFullFiveInnerTwoDirectGroup0Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup0BaseOrder11_contains

end
end RiemannVenue.Venue
