import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerThreeDirectGroup11GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerThreeDirectGroup11Group n b g

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerThreeDirectGroup11Group_contains n b g

def computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval where
  signed := computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed_contains n b

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval where
  bump := computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump_contains b n

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0 : RationalInterval :=
  ⟨(6182206849965771 : ℚ) / 1000000000000000000, (539 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1 : RationalInterval :=
  ⟨(145352709005978653 : ℚ) / 2000000000000000000, (39881 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2 : RationalInterval :=
  ⟨(351566448951868273 : ℚ) / 2000000000000000000, (787879 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3 : RationalInterval :=
  ⟨(-69716620125506315537 : ℚ) / 2000000000000000000, (16753551 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4 : RationalInterval :=
  ⟨(34103537436905317523 : ℚ) / 2000000000000000000, (387451337 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5 : RationalInterval :=
  ⟨(32103484831172775700641 : ℚ) / 500000000000000000, (4959479711 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6 : RationalInterval :=
  ⟨(273677220807912071875929 : ℚ) / 2000000000000000000, (279015937849 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7 : RationalInterval :=
  ⟨(-275835222323448553182082611 : ℚ) / 2000000000000000000, (1743813078077 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder7,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8 : RationalInterval :=
  ⟨(-2090055110472026253099065881 : ℚ) / 2000000000000000000, (290833129502837 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder8,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9 : RationalInterval :=
  ⟨(72392477929647080705347231281 : ℚ) / 250000000000000000, (2612331888661607 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder9,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10 : RationalInterval :=
  ⟨(7449421469408417330793046860147 : ℚ) / 2000000000000000000, (77126072269161849 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder10,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11 : RationalInterval :=
  ⟨(-596019002890316858510553759350117 : ℚ) / 1000000000000000000, (7447865316427855137 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup11Group, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup11GroupOrder11,
    computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup11Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder10Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup11BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10,
  computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11
]

def computedPhasedBaseFullFiveInnerThreeDirectGroup11Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerThreeCompactCell1Shard14Interval.center where
  base := computedPhasedBaseFullFiveInnerThreeDirectGroup11Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup11BaseOrder11_contains

end
end RiemannVenue.Venue
