import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerThreeDirectGroup22GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerThreeDirectGroup22Group n b g

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerThreeDirectGroup22Group_contains n b g

def computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval where
  signed := computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed_contains n b

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval where
  bump := computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump_contains b n

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0 : RationalInterval :=
  ⟨(5328450374131001 : ℚ) / 400000000000000000, (2233 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1 : RationalInterval :=
  ⟨(80173762473003833 : ℚ) / 2000000000000000000, (8887 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2 : RationalInterval :=
  ⟨(-1118069254379804189 : ℚ) / 1000000000000000000, (494247 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3 : RationalInterval :=
  ⟨(-121942382400490863031 : ℚ) / 2000000000000000000, (1021027 : ℚ) / 80000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4 : RationalInterval :=
  ⟨(-460396988261198753291 : ℚ) / 1000000000000000000, (75814923 : ℚ) / 200000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5 : RationalInterval :=
  ⟨(1924257803900804025993 : ℚ) / 20000000000000000, (12798090179 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6 : RationalInterval :=
  ⟨(871545941376791281476497 : ℚ) / 500000000000000000, (117214846359 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7 : RationalInterval :=
  ⟨(-11258076933100661392122361 : ℚ) / 62500000000000000, (18223679438571 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder7,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8 : RationalInterval :=
  ⟨(-9106705039850827680058146163 : ℚ) / 2000000000000000000, (291103225236359 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder8,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9 : RationalInterval :=
  ⟨(139418829458392675802500790947 : ℚ) / 400000000000000000, (59489875203114071 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder9,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10 : RationalInterval :=
  ⟨(5643601694820880626751687306061 : ℚ) / 500000000000000000, (1223625072306846343 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder10,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11 : RationalInterval :=
  ⟨(-267459359536878960596475668937141 : ℚ) / 400000000000000000, (101788525446915281541 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup22Group, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup22GroupOrder11,
    computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup22Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder10Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup22BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10,
  computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11
]

def computedPhasedBaseFullFiveInnerThreeDirectGroup22Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerThreeCompactCell3Shard11Interval.center where
  base := computedPhasedBaseFullFiveInnerThreeDirectGroup22Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup22BaseOrder11_contains

end
end RiemannVenue.Venue
