import RiemannVenue.Venue.BoundaryCanonicalBumpTransformPacketGrid

/-!
# Canonical-bump transform packet: Correction1Plus

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

open MeasureTheory Set
open scoped BigOperators Interval

noncomputable section

def canonicalBumpCorrection1PlusReal : ℚ := (20313615198428573 / 200000000000000 : ℚ)

theorem canonicalBumpCorrection1PlusReal_bound : |canonicalBumpCorrection1PlusReal| ≤ 103 := by
  norm_num [canonicalBumpCorrection1PlusReal]

theorem canonicalBumpCorrection1Plus_kernel_trig (i : Fin 128) :
    |(((canonicalBumpCorrection1PlusReal * canonicalBumpPacketMidpoint i : ℚ) : ℝ) / 16)| / 33 ≤
      (1 : ℝ) / 2 := by
  have hre : |(canonicalBumpCorrection1PlusReal : ℝ)| ≤ 103 := by
    exact_mod_cast canonicalBumpCorrection1PlusReal_bound
  push_cast
  rw [abs_div, abs_mul]
  norm_num
  calc
    |(canonicalBumpCorrection1PlusReal : ℝ)| * |(canonicalBumpPacketMidpoint i : ℝ)| / 16 / 33 ≤
        103 * 1 / 16 / 33 := by
      gcongr
      exact canonicalBumpPacket_midpoint_abs i
    _ ≤ (1 : ℝ) / 2 := by norm_num

noncomputable def canonicalBumpCorrection1PlusCell (i : Fin 128) :
    ComplexIntegralCellCertificate
      (computedTransformRawIntegrand canonicalSmoothBump
        ((canonicalBumpCorrection1PlusReal : ℝ) +
          (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
      (equalCellPoint (-1) 1 128 i)
      (equalCellPoint (-1) 1 128 (i + 1)) :=
  canonicalBumpPacketTransportCell
    (canonicalBumpTaylorCellAt
    canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
    (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius
    canonicalBumpPacket_radius_nonneg
    canonicalBumpCorrection1PlusReal_bound canonicalBumpPacket_imaginary_bound
    (canonicalBumpPacket_kernel_exp i)
    (canonicalBumpCorrection1Plus_kernel_trig i)
    (canonicalBumpPacket_bump_lower i)
    (canonicalBumpPacket_bump_upper i)
    (canonicalBumpPacket_window i))
    (canonicalBumpPacket_left_geometry_real i)
    (canonicalBumpPacket_right_geometry_real i)

noncomputable def canonicalBumpCorrection1PlusPacket :
    EqualCellComplexTaylorCertificate
      (computedTransformRawIntegrand canonicalSmoothBump
        ((canonicalBumpCorrection1PlusReal : ℝ) +
          (canonicalBumpPacketImaginaryPart : ℝ) * Complex.I))
      (-1) 1 128 12 where
  cells_pos := by norm_num
  ordered := by norm_num
  integrable := fun _ =>
    (canonicalBumpRawIntegrand_contDiff _).continuous.intervalIntegrable _ _
  cell := canonicalBumpCorrection1PlusCell

def canonicalBumpCorrection1PlusRawCenterQ : ℚ × ℚ :=
  (∑ i : Fin 128, (canonicalBumpCellCenterQ
      canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
      (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius).re.center,
    ∑ i : Fin 128, (canonicalBumpCellCenterQ
      canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
      (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius).im.center)

def canonicalBumpCorrection1PlusRawErrorQ : ℚ :=
  ∑ i : Fin 128, canonicalBumpCellErrorQ
    canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
    (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius

theorem canonicalBumpCorrection1PlusCell_center (i : Fin 128) :
    (canonicalBumpCorrection1PlusCell i).center =
      ((canonicalBumpCellCenterQ
        canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
        (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius).re.center : ℝ) +
      ((canonicalBumpCellCenterQ
        canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
        (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius).im.center : ℝ) *
        Complex.I := by
  rw [canonicalBumpCorrection1PlusCell, canonicalBumpPacketTransportCell_center]
  exact canonicalBumpTaylorCellAt_center
      canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
      (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius
      canonicalBumpPacket_radius_nonneg
      canonicalBumpCorrection1PlusReal_bound canonicalBumpPacket_imaginary_bound
      (canonicalBumpPacket_kernel_exp i)
      (canonicalBumpCorrection1Plus_kernel_trig i)
      (canonicalBumpPacket_bump_lower i)
      (canonicalBumpPacket_bump_upper i)
      (canonicalBumpPacket_window i)

theorem canonicalBumpCorrection1PlusCell_error (i : Fin 128) :
    (canonicalBumpCorrection1PlusCell i).error =
      (canonicalBumpCellErrorQ
        canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
        (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius : ℝ) := by
  rw [canonicalBumpCorrection1PlusCell, canonicalBumpPacketTransportCell_error]
  exact canonicalBumpTaylorCellAt_error
      canonicalBumpCorrection1PlusReal canonicalBumpPacketImaginaryPart
      (canonicalBumpPacketMidpoint i) canonicalBumpPacketRadius
      canonicalBumpPacket_radius_nonneg
      canonicalBumpCorrection1PlusReal_bound canonicalBumpPacket_imaginary_bound
      (canonicalBumpPacket_kernel_exp i)
      (canonicalBumpCorrection1Plus_kernel_trig i)
      (canonicalBumpPacket_bump_lower i)
      (canonicalBumpPacket_bump_upper i)
      (canonicalBumpPacket_window i)

theorem canonicalBumpCorrection1PlusPacket_center :
    canonicalBumpCorrection1PlusPacket.center =
      ((canonicalBumpCorrection1PlusRawCenterQ.1 : ℚ) : ℝ) +
        ((canonicalBumpCorrection1PlusRawCenterQ.2 : ℚ) : ℝ) * Complex.I := by
  rw [EqualCellComplexTaylorCertificate.center]
  unfold canonicalBumpCorrection1PlusPacket canonicalBumpCorrection1PlusRawCenterQ
  simp_rw [show ∀ i : Fin 128,
    (canonicalBumpCorrection1PlusCell i).center = _ from canonicalBumpCorrection1PlusCell_center]
  push_cast
  rw [Finset.sum_add_distrib, Finset.sum_mul]

theorem canonicalBumpCorrection1PlusPacket_error :
    canonicalBumpCorrection1PlusPacket.error = (canonicalBumpCorrection1PlusRawErrorQ : ℝ) := by
  rw [EqualCellComplexTaylorCertificate.error]
  unfold canonicalBumpCorrection1PlusPacket canonicalBumpCorrection1PlusRawErrorQ
  simp_rw [canonicalBumpCorrection1PlusCell_error]
  push_cast
  rfl

end

end RiemannVenue.Venue
