import RiemannVenue.Venue.BoundaryComputedPhasedBumpQuadratureTable

/-! Kernel-checked bump quadrature leaves for jet 2, block 5. Generated by `scripts/generate_computed_phased_bump_quadrature.py`. -/
namespace RiemannVenue.Venue
noncomputable section

set_option maxRecDepth 100000

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_80 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨80, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨80, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨80, by norm_num⟩)).absUpper ≤
      (2309373/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_81 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨81, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨81, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨81, by norm_num⟩)).absUpper ≤
      (4680703/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_82 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨82, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨82, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨82, by norm_num⟩)).absUpper ≤
      (237187/50000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_83 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨83, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨83, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨83, by norm_num⟩)).absUpper ≤
      (4807871/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_84 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨84, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨84, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨84, by norm_num⟩)).absUpper ≤
      (609139/125000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_85 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨85, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨85, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨85, by norm_num⟩)).absUpper ≤
      (2469739/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_86 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨86, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨86, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨86, by norm_num⟩)).absUpper ≤
      (2503493/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_87 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨87, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨87, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨87, by norm_num⟩)).absUpper ≤
      (101513/20000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_88 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨88, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨88, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨88, by norm_num⟩)).absUpper ≤
      (5145487/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_89 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨89, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨89, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨89, by norm_num⟩)).absUpper ≤
      (5216511/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_90 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨90, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨90, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨90, by norm_num⟩)).absUpper ≤
      (2644369/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_91 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨91, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨91, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨91, by norm_num⟩)).absUpper ≤
      (5362183/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_92 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨92, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨92, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨92, by norm_num⟩)).absUpper ≤
      (5436861/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_93 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨93, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨93, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨93, by norm_num⟩)).absUpper ≤
      (2756393/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_94 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨94, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨94, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨94, by norm_num⟩)).absUpper ≤
      (5589973/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_95 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨95, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨95, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨95, by norm_num⟩)).absUpper ≤
      (1133687/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]


end
end RiemannVenue.Venue
