import RiemannVenue.Venue.BoundaryCanonicalBumpKernelRecurrence
import RiemannVenue.Venue.BoundaryCanonicalBumpTransformPacketCorrection0Plus

/-!
# Canonical-bump kernel recurrence: Correction0Plus forward

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

noncomputable section

set_option maxHeartbeats 2000000
set_option maxRecDepth 100000

def canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial : RationalRectangle :=
  ⟨⟨(72532213970327 / 100000000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩, ⟨(33923773163751 / 50000000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceStep : RationalRectangle :=
  ⟨⟨(1644081301937 / 25000000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩, ⟨(1230283186897 / 1250000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel00 : RationalRectangle :=
  ⟨⟨(72532213970327 / 100000000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩, ⟨(33923773163751 / 50000000000000 : ℚ), (1 / 1000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel01 : RationalRectangle :=
  ⟨⟨(-15501850536021 / 25000000000000 : ℚ), (247 / 100000000000000 : ℚ)⟩, ⟨(75850005976861 / 100000000000000 : ℚ), (247 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel02 : RationalRectangle :=
  ⟨⟨(-39365699040683 / 50000000000000 : ℚ), (399 / 100000000000000 : ℚ)⟩, ⟨(-56041188393687 / 100000000000000 : ℚ), (399 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel03 : RationalRectangle :=
  ⟨⟨(49979592705147 / 100000000000000 : ℚ), (111 / 20000000000000 : ℚ)⟩, ⟨(-649399864571 / 800000000000 : ℚ), (111 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel04 : RationalRectangle :=
  ⟨⟨(83181394049287 / 100000000000000 : ℚ), (179 / 25000000000000 : ℚ)⟩, ⟨(21926455600187 / 50000000000000 : ℚ), (179 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel05 : RationalRectangle :=
  ⟨⟨(-18845460246013 / 50000000000000 : ℚ), (881 / 100000000000000 : ℚ)⟩, ⟨(16950649300559 / 20000000000000 : ℚ), (11 / 1250000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel06 : RationalRectangle :=
  ⟨⟨(-8589507287121 / 10000000000000 : ℚ), (131 / 12500000000000 : ℚ)⟩, ⟨(-31522755509861 / 100000000000000 : ℚ), (1049 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel07 : RationalRectangle :=
  ⟨⟨(5075358711463 / 20000000000000 : ℚ), (1221 / 100000000000000 : ℚ)⟩, ⟨(-43306625054683 / 50000000000000 : ℚ), (61 / 5000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel08 : RationalRectangle :=
  ⟨⟨(43457960384637 / 50000000000000 : ℚ), (279 / 20000000000000 : ℚ)⟩, ⟨(3856108992109 / 20000000000000 : ℚ), (349 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel09 : RationalRectangle :=
  ⟨⟨(-165756882903 / 1250000000000 : ℚ), (787 / 50000000000000 : ℚ)⟩, ⟨(86812908135319 / 100000000000000 : ℚ), (1573 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel10 : RationalRectangle :=
  ⟨⟨(-10789453245191 / 12500000000000 : ℚ), (877 / 50000000000000 : ℚ)⟩, ⟨(-7342286832191 / 100000000000000 : ℚ), (877 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel11 : RationalRectangle :=
  ⟨⟨(775038683041 / 50000000000000 : ℚ), (1937 / 100000000000000 : ℚ)⟩, ⟨(-85436983369337 / 100000000000000 : ℚ), (1937 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel12 : RationalRectangle :=
  ⟨⟨(131548883549 / 156250000000 : ℚ), (2123 / 100000000000000 : ℚ)⟩, ⟨(-4092986576553 / 100000000000000 : ℚ), (1061 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel13 : RationalRectangle :=
  ⟨⟨(9565118784643 / 100000000000000 : ℚ), (1159 / 50000000000000 : ℚ)⟩, ⟨(322633321449 / 390625000000 : ℚ), (2319 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel14 : RationalRectangle :=
  ⟨⟨(-80662302548877 / 100000000000000 : ℚ), (2529 / 100000000000000 : ℚ)⟩, ⟨(14845902467579 / 100000000000000 : ℚ), (79 / 3125000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel15 : RationalRectangle :=
  ⟨⟨(-4979086673953 / 25000000000000 : ℚ), (43 / 1562500000000 : ℚ)⟩, ⟨(-78413664887533 / 100000000000000 : ℚ), (2753 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel16 : RationalRectangle :=
  ⟨⟨(75867047099067 / 100000000000000 : ℚ), (2991 / 100000000000000 : ℚ)⟩, ⟨(-24758934797733 / 100000000000000 : ℚ), (299 / 10000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel17 : RationalRectangle :=
  ⟨⟨(14678832354227 / 50000000000000 : ℚ), (1621 / 50000000000000 : ℚ)⟩, ⟨(73042133918131 / 100000000000000 : ℚ), (3243 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel18 : RationalRectangle :=
  ⟨⟨(-8744918991377 / 12500000000000 : ℚ), (3509 / 100000000000000 : ℚ)⟩, ⟨(33698081303031 / 100000000000000 : ℚ), (877 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel19 : RationalRectangle :=
  ⟨⟨(-18883650391231 / 50000000000000 : ℚ), (3789 / 100000000000000 : ℚ)⟩, ⟨(-66639756142293 / 100000000000000 : ℚ), (379 / 10000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel20 : RationalRectangle :=
  ⟨⟨(3155245836349 / 5000000000000 : ℚ), (2043 / 50000000000000 : ℚ)⟩, ⟨(-41554027215283 / 100000000000000 : ℚ), (817 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel21 : RationalRectangle :=
  ⟨⟨(45048561370703 / 100000000000000 : ℚ), (1099 / 25000000000000 : ℚ)⟩, ⟨(29688403240599 / 50000000000000 : ℚ), (1099 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel22 : RationalRectangle :=
  ⟨⟨(-27738844733607 / 50000000000000 : ℚ), (2361 / 50000000000000 : ℚ)⟩, ⟨(24121401005399 / 50000000000000 : ℚ), (2361 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel23 : RationalRectangle :=
  ⟨⟨(-51130239839257 / 100000000000000 : ℚ), (5063 / 100000000000000 : ℚ)⟩, ⟨(-10286002265993 / 20000000000000 : ℚ), (5063 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel24 : RationalRectangle :=
  ⟨⟨(47256291741611 / 100000000000000 : ℚ), (5421 / 100000000000000 : ℚ)⟩, ⟨(-53705944332439 / 100000000000000 : ℚ), (5421 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel25 : RationalRectangle :=
  ⟨⟨(55966543704951 / 100000000000000 : ℚ), (1159 / 20000000000000 : ℚ)⟩, ⟨(859580388173 / 2000000000000 : ℚ), (1159 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel26 : RationalRectangle :=
  ⟨⟨(-9655137513163 / 25000000000000 : ℚ), (3093 / 50000000000000 : ℚ)⟩, ⟨(14477549571641 / 25000000000000 : ℚ), (1237 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel27 : RationalRectangle :=
  ⟨⟨(-14884141902487 / 25000000000000 : ℚ), (6593 / 100000000000000 : ℚ)⟩, ⟨(-34203007751017 / 100000000000000 : ℚ), (6593 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel28 : RationalRectangle :=
  ⟨⟨(14874094999173 / 50000000000000 : ℚ), (3509 / 50000000000000 : ℚ)⟩, ⟨(-60846771529399 / 100000000000000 : ℚ), (3509 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel29 : RationalRectangle :=
  ⟨⟨(966302276709 / 1562500000000 : ℚ), (7461 / 100000000000000 : ℚ)⟩, ⟨(25277476822277 / 100000000000000 : ℚ), (7461 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel30 : RationalRectangle :=
  ⟨⟨(-208117442601 / 1000000000000 : ℚ), (7923 / 100000000000000 : ℚ)⟩, ⟨(62530191838309 / 100000000000000 : ℚ), (7923 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel31 : RationalRectangle :=
  ⟨⟨(-62912522937641 / 100000000000000 : ℚ), (2101 / 25000000000000 : ℚ)⟩, ⟨(-3274256494849 / 20000000000000 : ℚ), (2101 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel32 : RationalRectangle :=
  ⟨⟨(5987859378013 / 50000000000000 : ℚ), (1781 / 20000000000000 : ℚ)⟩, ⟨(-62996804148547 / 100000000000000 : ℚ), (1781 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel33 : RationalRectangle :=
  ⟨⟨(31395344694561 / 50000000000000 : ℚ), (9427 / 100000000000000 : ℚ)⟩, ⟨(382197281897 / 5000000000000 : ℚ), (9427 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel34 : RationalRectangle :=
  ⟨⟨(-1697027152757 / 50000000000000 : ℚ), (997 / 10000000000000 : ℚ)⟩, ⟨(62302954283141 / 100000000000000 : ℚ), (9971 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel35 : RationalRectangle :=
  ⟨⟨(-61543425767707 / 100000000000000 : ℚ), (10537 / 100000000000000 : ℚ)⟩, ⟨(756726529703 / 100000000000000 : ℚ), (1317 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel36 : RationalRectangle :=
  ⟨⟨(-4792086163731 / 100000000000000 : ℚ), (11127 / 100000000000000 : ℚ)⟩, ⟨(-15130727197829 / 25000000000000 : ℚ), (1391 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel37 : RationalRectangle :=
  ⟨⟨(59253110516083 / 100000000000000 : ℚ), (11751 / 100000000000000 : ℚ)⟩, ⟨(-4348340868613 / 50000000000000 : ℚ), (47 / 400000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel38 : RationalRectangle :=
  ⟨⟨(12456182301727 / 100000000000000 : ℚ), (12407 / 100000000000000 : ℚ)⟩, ⟨(57746562438107 / 100000000000000 : ℚ), (1551 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel39 : RationalRectangle :=
  ⟨⟨(-56016540838329 / 100000000000000 : ℚ), (131 / 1000000000000 : ℚ)⟩, ⟨(501790845913 / 3125000000000 : ℚ), (13099 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel40 : RationalRectangle :=
  ⟨⟨(-19487857826939 / 100000000000000 : ℚ), (3457 / 25000000000000 : ℚ)⟩, ⟨(-27038492986371 / 50000000000000 : ℚ), (3457 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel41 : RationalRectangle :=
  ⟨⟨(2597121020277 / 5000000000000 : ℚ), (2919 / 20000000000000 : ℚ)⟩, ⟨(-11368372763307 / 50000000000000 : ℚ), (2919 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel42 : RationalRectangle :=
  ⟨⟨(25794011083563 / 100000000000000 : ℚ), (15401 / 100000000000000 : ℚ)⟩, ⟨(49627866881849 / 100000000000000 : ℚ), (15401 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel43 : RationalRectangle :=
  ⟨⟨(-47148766128063 / 100000000000000 : ℚ), (2031 / 12500000000000 : ℚ)⟩, ⟨(28650840446813 / 100000000000000 : ℚ), (2031 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel44 : RationalRectangle :=
  ⟨⟨(-3912446753221 / 12500000000000 : ℚ), (8569 / 50000000000000 : ℚ)⟩, ⟨(-445208949577 / 1000000000000 : ℚ), (8569 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel45 : RationalRectangle :=
  ⟨⟨(20880142524539 / 50000000000000 : ℚ), (2259 / 12500000000000 : ℚ)⟩, ⟨(-33733710582571 / 100000000000000 : ℚ), (2259 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel46 : RationalRectangle :=
  ⟨⟨(35947905721619 / 100000000000000 : ℚ), (19053 / 100000000000000 : ℚ)⟩, ⟨(1555325709927 / 4000000000000 : ℚ), (4763 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel47 : RationalRectangle :=
  ⟨⟨(-1122055319869 / 3125000000000 : ℚ), (20081 / 100000000000000 : ℚ)⟩, ⟨(18968982564443 / 50000000000000 : ℚ), (10041 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel48 : RationalRectangle :=
  ⟨⟨(-4962604091697 / 12500000000000 : ℚ), (21161 / 100000000000000 : ℚ)⟩, ⟨(-32844488382883 / 100000000000000 : ℚ), (21161 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel49 : RationalRectangle :=
  ⟨⟨(7428890400253 / 25000000000000 : ℚ), (22293 / 100000000000000 : ℚ)⟩, ⟨(-20617286991611 / 50000000000000 : ℚ), (22293 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel50 : RationalRectangle :=
  ⟨⟨(21269177220263 / 50000000000000 : ℚ), (587 / 2500000000000 : ℚ)⟩, ⟨(3316890622297 / 12500000000000 : ℚ), (587 / 2500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel51 : RationalRectangle :=
  ⟨⟨(-5829778493113 / 25000000000000 : ℚ), (989 / 4000000000000 : ℚ)⟩, ⟨(340721983797 / 781250000000 : ℚ), (6181 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel52 : RationalRectangle :=
  ⟨⟨(-4445803644493 / 10000000000000 : ℚ), (26029 / 100000000000000 : ℚ)⟩, ⟨(-2008319691219 / 10000000000000 : ℚ), (26029 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel53 : RationalRectangle :=
  ⟨⟨(1684271054257 / 10000000000000 : ℚ), (27397 / 100000000000000 : ℚ)⟩, ⟨(-45077516149579 / 100000000000000 : ℚ), (6849 / 25000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel54 : RationalRectangle :=
  ⟨⟨(45474119599803 / 100000000000000 : ℚ), (28829 / 100000000000000 : ℚ)⟩, ⟨(6806299412133 / 50000000000000 : ℚ), (2883 / 10000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel55 : RationalRectangle :=
  ⟨⟨(-10407355180531 / 100000000000000 : ℚ), (7583 / 25000000000000 : ℚ)⟩, ⟨(1826081783759 / 4000000000000 : ℚ), (30331 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel56 : RationalRectangle :=
  ⟨⟨(-45616375851349 / 100000000000000 : ℚ), (6381 / 20000000000000 : ℚ)⟩, ⟨(-1810242090613 / 25000000000000 : ℚ), (15953 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel57 : RationalRectangle :=
  ⟨⟨(4126872082569 / 100000000000000 : ℚ), (6711 / 20000000000000 : ℚ)⟩, ⟨(-1417907432293 / 3125000000000 : ℚ), (6711 / 20000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel58 : RationalRectangle :=
  ⟨⟨(44928744996933 / 100000000000000 : ℚ), (8821 / 25000000000000 : ℚ)⟩, ⟨(107789854557 / 10000000000000 : ℚ), (35283 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel59 : RationalRectangle :=
  ⟨⟨(946882008261 / 50000000000000 : ℚ), (7419 / 20000000000000 : ℚ)⟩, ⟨(22145474888127 / 50000000000000 : ℚ), (4637 / 12500000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel60 : RationalRectangle :=
  ⟨⟨(-21733894296373 / 50000000000000 : ℚ), (19499 / 50000000000000 : ℚ)⟩, ⟨(4776609718469 / 100000000000000 : ℚ), (38997 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel61 : RationalRectangle :=
  ⟨⟨(-1889962310019 / 25000000000000 : ℚ), (40997 / 100000000000000 : ℚ)⟩, ⟨(-42468026192807 / 100000000000000 : ℚ), (20499 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel62 : RationalRectangle :=
  ⟨⟨(41300998613327 / 100000000000000 : ℚ), (43099 / 100000000000000 : ℚ)⟩, ⟨(-1279179980523 / 12500000000000 : ℚ), (21549 / 50000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel63 : RationalRectangle :=
  ⟨⟨(12788111170397 / 100000000000000 : ℚ), (22653 / 50000000000000 : ℚ)⟩, ⟨(39976555072733 / 100000000000000 : ℚ), (45307 / 100000000000000 : ℚ)⟩⟩
def canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels : Fin 64 → RationalRectangle := ![
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel00,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel01,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel02,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel03,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel04,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel05,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel06,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel07,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel08,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel09,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel10,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel11,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel12,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel13,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel14,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel15,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel16,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel17,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel18,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel19,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel20,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel21,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel22,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel23,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel24,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel25,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel26,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel27,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel28,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel29,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel30,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel31,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel32,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel33,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel34,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel35,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel36,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel37,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel38,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel39,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel40,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel41,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel42,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel43,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel44,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel45,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel46,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel47,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel48,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel49,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel50,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel51,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel52,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel53,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel54,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel55,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel56,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel57,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel58,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel59,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel60,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel61,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel62,
  canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel63
]

theorem canonicalBumpCorrection0PlusForwardKernelRecurrence_initial_contains :
    canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial.Contains
      (Complex.exp (Complex.I *
        (((canonicalBumpCorrection0PlusReal : ℚ) : ℝ) +
          ((canonicalBumpPacketImaginaryPart : ℚ) : ℝ) * Complex.I) *
        (((1 / 128 : ℚ) : ℝ) : ℂ))) := by
  have hraw := rationalComplexKernelInterval_contains
    (expOrder := 32) (expReduction := 1) (trigOrder := 32)
    (trigHalvings := 4) (re := canonicalBumpCorrection0PlusReal) (im := canonicalBumpPacketImaginaryPart)
    (t := (1 / 128 : ℚ)) (by norm_num)
    (by norm_num [canonicalBumpCorrection0PlusReal,
      canonicalBumpPacketImaginaryPart, abs_div])
    (by norm_num [canonicalBumpCorrection0PlusReal,
      canonicalBumpPacketImaginaryPart, abs_div])
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]

theorem canonicalBumpCorrection0PlusForwardKernelRecurrence_step_contains :
    canonicalBumpCorrection0PlusForwardKernelRecurrenceStep.Contains
      (Complex.exp (Complex.I *
        (((canonicalBumpCorrection0PlusReal : ℚ) : ℝ) +
          ((canonicalBumpPacketImaginaryPart : ℚ) : ℝ) * Complex.I) *
        (((1 / 64 : ℚ) : ℝ) : ℂ))) := by
  have hraw := rationalComplexKernelInterval_contains
    (expOrder := 32) (expReduction := 1) (trigOrder := 32)
    (trigHalvings := 4) (re := canonicalBumpCorrection0PlusReal) (im := canonicalBumpPacketImaginaryPart)
    (t := (1 / 64 : ℚ)) (by norm_num)
    (by norm_num [canonicalBumpCorrection0PlusReal,
      canonicalBumpPacketImaginaryPart, abs_div])
    (by norm_num [canonicalBumpCorrection0PlusReal,
      canonicalBumpPacketImaginaryPart, abs_div])
  apply RationalRectangle.contains_of_wide hraw
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]
  · norm_num (config := { maxSteps := 1000000 }) [
      canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep, canonicalBumpCorrection0PlusReal, canonicalBumpPacketImaginaryPart,
      rationalComplexKernelInterval, rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, rationalTrigInterval, RationalTrigInterval.reconstruct, RationalTrigInterval.taylor,
      RationalTrigInterval.double, rationalCisTaylor, rationalCisMonomial, RationalComplex.add,
      RationalComplex.scale, RationalComplex.mulArgI, RationalComplex.zero, RationalComplex.one,
      RationalRectangle.mul, RationalInterval.pow, RationalInterval.mul, RationalInterval.sub,
      RationalInterval.add, RationalInterval.neg, RationalInterval.one, RationalInterval.zero,
      RationalInterval.singleton, Finset.sum_range_succ
    ]

def canonicalBumpCorrection0PlusForwardKernelRecurrence : PositiveHalfKernelRecurrenceCertificate
    (((canonicalBumpCorrection0PlusReal : ℚ) : ℝ)) (((canonicalBumpPacketImaginaryPart : ℚ) : ℝ)) where
  initial := canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial
  step := canonicalBumpCorrection0PlusForwardKernelRecurrenceStep
  kernels := canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels
  initial_contains := by
    simpa [canonicalBumpPositiveGridKernel,
      canonicalBumpPositiveGridPoint, canonicalBumpPositiveGridPointQ] using
      canonicalBumpCorrection0PlusForwardKernelRecurrence_initial_contains
  step_contains := by
    simpa [canonicalBumpPositiveGridStepKernel,
      canonicalBumpPositiveGridStep] using
      canonicalBumpCorrection0PlusForwardKernelRecurrence_step_contains
  kernel_zero_widens := by
    norm_num [canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceInitial,
      canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel00,
      RationalRectangle.Widens, RationalInterval.Widens]
  successor_widens i := by
    fin_cases i
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel00,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel01,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel01,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel02,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel02,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel03,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel03,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel04,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel04,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel05,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel05,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel06,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel06,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel07,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel07,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel08,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel08,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel09,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel09,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel10,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel10,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel11,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel11,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel12,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel12,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel13,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel13,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel14,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel14,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel15,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel15,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel16,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel16,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel17,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel17,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel18,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel18,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel19,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel19,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel20,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel20,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel21,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel21,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel22,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel22,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel23,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel23,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel24,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel24,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel25,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel25,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel26,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel26,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel27,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel27,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel28,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel28,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel29,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel29,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel30,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel30,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel31,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel31,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel32,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel32,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel33,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel33,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel34,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel34,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel35,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel35,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel36,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel36,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel37,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel37,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel38,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel38,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel39,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel39,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel40,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel40,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel41,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel41,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel42,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel42,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel43,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel43,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel44,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel44,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel45,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel45,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel46,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel46,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel47,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel47,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel48,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel48,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel49,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel49,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel50,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel50,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel51,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel51,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel52,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel52,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel53,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel53,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel54,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel54,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel55,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel55,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel56,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel56,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel57,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel57,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel58,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel58,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel59,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel59,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel60,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel60,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel61,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel61,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel62,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]
    · norm_num (config := { maxSteps := 1000000 }) [
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernels, canonicalBumpCorrection0PlusForwardKernelRecurrenceStep,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel62,
        canonicalBumpCorrection0PlusForwardKernelRecurrenceKernel63,
        positiveKernelSuccessorIndex, positiveKernelCurrentIndex,
        RationalRectangle.Widens, RationalInterval.Widens,
        RationalRectangle.mul, RationalInterval.mul,
        RationalInterval.sub, RationalInterval.add,
        RationalInterval.neg, RationalInterval.lower,
        RationalInterval.upper]

end

end RiemannVenue.Venue
