import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerTwoDirectGroup34GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerTwoDirectGroup34Group n b g

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerTwoDirectGroup34Group_contains n b g

def computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval where
  signed := computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed_contains n b

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval where
  bump := computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump_contains b n

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0 : RationalInterval :=
  ⟨(-113482782466628819 : ℚ) / 500000000000000000, (2103779 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1 : RationalInterval :=
  ⟨(-69873398789175319 : ℚ) / 1000000000000000000, (89469337 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2 : RationalInterval :=
  ⟨(116167634467704578437 : ℚ) / 2000000000000000000, (7612258693 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3 : RationalInterval :=
  ⟨(638711143577952584123 : ℚ) / 500000000000000000, (5061162037 : ℚ) / 31250000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4 : RationalInterval :=
  ⟨(-18612035796335008541179 : ℚ) / 1000000000000000000, (3446554140961 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5 : RationalInterval :=
  ⟨(-213247694092827063325529 : ℚ) / 125000000000000000, (293446248807227 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6 : RationalInterval :=
  ⟨(719575659393238955392361 : ℚ) / 80000000000000000, (24990417938592221 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7 : RationalInterval :=
  ⟨(2872403651879088028555790587 : ℚ) / 1000000000000000000, (266093691671445941 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder7,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8 : RationalInterval :=
  ⟨(17217469080672759259688748657 : ℚ) / 2000000000000000000, (9068946034116002099 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder8,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9 : RationalInterval :=
  ⟨(-2532932050539276522642203029533 : ℚ) / 500000000000000000, (966152877413635194433 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder9,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10 : RationalInterval :=
  ⟨(-57113387264706328358967167534953 : ℚ) / 1000000000000000000, (41182962416193728128859 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder10,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11 : RationalInterval :=
  ⟨(3517780808123324571226762584919741 : ℚ) / 400000000000000000, (3511949669711068813179191 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup34Group, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup34GroupOrder11,
    computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup34Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder10Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup34BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10,
  computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11
]

def computedPhasedBaseFullFiveInnerTwoDirectGroup34Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerTwoCompactCell5Shard22Interval.center where
  base := computedPhasedBaseFullFiveInnerTwoDirectGroup34Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup34BaseOrder11_contains

end
end RiemannVenue.Venue
