import RiemannVenue.Venue.BoundaryCanonicalBumpPairedTransformPacketCorrection1MinusData

/-!
# Paired canonical-bump packet: Correction1Minus, block 09

Generated by `scripts/generate_canonical_bump_transform_packets.py`. Do not edit by hand.
All packet data are exact rationals; Lean remains proof authority.
-/

namespace RiemannVenue.Venue

noncomputable section

set_option maxHeartbeats 8000000
set_option maxRecDepth 100000

theorem canonicalBumpCorrection1MinusPairedBlock09Data_eq :
    canonicalBumpPairedPositiveBlockDataQ
      canonicalBumpCorrection1MinusReal canonicalBumpCorrection1MinusPairedRecurrences
      (9 : Fin 16) =
      { re := (2377715058489876484059048400212585683613412535000159511084907 / 2024022219167607494946544100334108672000000000000000000000000000 : ℚ)
        im := (397092129600569774804060253503572433648973915164265765134196403 / 10120111095838037474732720501670543360000000000000000000000000000 : ℚ)
        error := (1035049851929111274719080650044211845963474035578251265728239 / 1295374220267268796765788224213829550080000000000000000000000000000 : ℚ) } := by
  decide +kernel

end

end RiemannVenue.Venue
