import RiemannVenue.Venue.BoundaryComputedPhasedBumpQuadratureTable

/-! Kernel-checked bump quadrature leaves for jet 2, block 0. Generated by `scripts/generate_computed_phased_bump_quadrature.py`. -/
namespace RiemannVenue.Venue
noncomputable section

set_option maxRecDepth 100000

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_0 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨0, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨0, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨0, by norm_num⟩)).absUpper ≤
      (2013857/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_1 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨1, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨1, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨1, by norm_num⟩)).absUpper ≤
      (507003/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_2 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨2, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨2, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨2, by norm_num⟩)).absUpper ≤
      (510613/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_3 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨3, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨3, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨3, by norm_num⟩)).absUpper ≤
      (64287/31250 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_4 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨4, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨4, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨4, by norm_num⟩)).absUpper ≤
      (2072211/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_5 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨5, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨5, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨5, by norm_num⟩)).absUpper ≤
      (2087539/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_6 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨6, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨6, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨6, by norm_num⟩)).absUpper ≤
      (2103173/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_7 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨7, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨7, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨7, by norm_num⟩)).absUpper ≤
      (2119117/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_8 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨8, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨8, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨8, by norm_num⟩)).absUpper ≤
      (2135377/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_9 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨9, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨9, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨9, by norm_num⟩)).absUpper ≤
      (1075979/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_10 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨10, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨10, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨10, by norm_num⟩)).absUpper ≤
      (433773/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_11 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨11, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨11, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨11, by norm_num⟩)).absUpper ≤
      (273263/125000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_12 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨12, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨12, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨12, by norm_num⟩)).absUpper ≤
      (13773/6250 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_13 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨13, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨13, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨13, by norm_num⟩)).absUpper ≤
      (1110799/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_14 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨14, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨14, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨14, by norm_num⟩)).absUpper ≤
      (447973/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_2_15 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      2 (computedPhasedBumpQuadratureCell ⟨15, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨2, by norm_num⟩ ⟨15, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 2
    (computedPhasedBumpQuadratureCell ⟨15, by norm_num⟩)).absUpper ≤
      (2258487/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]


end
end RiemannVenue.Venue
