import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerTwoDirectGroup38GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerTwoDirectGroup38Group n b g

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerTwoDirectGroup38Group_contains n b g

def computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval where
  signed := computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed_contains n b

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval where
  bump := computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump_contains b n

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0 : RationalInterval :=
  ⟨(-286335521662808639 : ℚ) / 2000000000000000000, (10484223 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1 : RationalInterval :=
  ⟨(7232447869314533489 : ℚ) / 2000000000000000000, (451338459 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2 : RationalInterval :=
  ⟨(73187075875838851737 : ℚ) / 1000000000000000000, (9711727781 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3 : RationalInterval :=
  ⟨(-449102979637133983957 : ℚ) / 500000000000000000, (26113540713 : ℚ) / 62500000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4 : RationalInterval :=
  ⟨(-22329716497136796904749 : ℚ) / 500000000000000000, (2246275198763 : ℚ) / 125000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5 : RationalInterval :=
  ⟨(1186856194728960208850057 : ℚ) / 1000000000000000000, (193176701701323 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6 : RationalInterval :=
  ⟨(4290946234119479337371709 : ℚ) / 62500000000000000, (33219062134759387 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7 : RationalInterval :=
  ⟨(-3440993450770465297955635803 : ℚ) / 2000000000000000000, (2855733795986842109 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder7,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8 : RationalInterval :=
  ⟨(-133205141758875920175930895317 : ℚ) / 1000000000000000000, (15341649703819537807 : ℚ) / 250000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder8,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9 : RationalInterval :=
  ⟨(840118823833370696169976160671 : ℚ) / 400000000000000000, (5274323632281994442203 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder9,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10 : RationalInterval :=
  ⟨(25648147997884746265101354008367 : ℚ) / 100000000000000000, (22664594959000145889237 : ℚ) / 200000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder10,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11 : RationalInterval :=
  ⟨(-373706861890215657616690339373027 : ℚ) / 200000000000000000, (4869584315425310801212543 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup38Group, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup38GroupOrder11,
    computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup38Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder10Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup38BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10,
  computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11
]

def computedPhasedBaseFullFiveInnerTwoDirectGroup38Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerTwoCompactCell6Shard12Interval.center where
  base := computedPhasedBaseFullFiveInnerTwoDirectGroup38Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup38BaseOrder11_contains

end
end RiemannVenue.Venue
