import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerThreeDirectGroup21GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerThreeDirectGroup21Group n b g

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerThreeDirectGroup21Group_contains n b g

def computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval where
  signed := computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed_contains n b

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval where
  bump := computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump_contains b n

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0 : RationalInterval :=
  ⟨(25414880320272389 : ℚ) / 2000000000000000000, (2219 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1 : RationalInterval :=
  ⟨(19959419676634591 : ℚ) / 400000000000000000, (43691 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2 : RationalInterval :=
  ⟨(-189180295113245343 : ℚ) / 500000000000000000, (239187 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3 : RationalInterval :=
  ⟨(-94193566517513607503 : ℚ) / 2000000000000000000, (24136223 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4 : RationalInterval :=
  ⟨(-190971316900600611941 : ℚ) / 125000000000000000, (175238793 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5 : RationalInterval :=
  ⟨(3684874795600464363083 : ℚ) / 62500000000000000, (2314635859 : ℚ) / 200000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6 : RationalInterval :=
  ⟨(1449968272436140133674521 : ℚ) / 400000000000000000, (837310107501 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7 : RationalInterval :=
  ⟨(-4659856713590175274582877 : ℚ) / 50000000000000000, (16081004503047 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder7,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8 : RationalInterval :=
  ⟨(-15963117938580149727822544701 : ℚ) / 2000000000000000000, (255922814627099 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder8,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9 : RationalInterval :=
  ⟨(299323786705184984316344529107 : ℚ) / 2000000000000000000, (51990981749987761 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder9,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10 : RationalInterval :=
  ⟨(17409581014782525430963834990089 : ℚ) / 1000000000000000000, (534620218582093011 : ℚ) / 500000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder10,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11 : RationalInterval :=
  ⟨(-444179896313971366560517999445597 : ℚ) / 2000000000000000000, (88640243455582093619 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8PointInterval, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval])

theorem computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11_contains : computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21SignedCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Signed, computedPhasedBaseFullFiveInnerThreeDirectGroup21Group, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup21GroupOrder11,
    computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpCache, computedPhasedBaseFullFiveInnerThreeDirectGroup21Bump, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder0Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder1Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder2Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder3Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder4Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder5Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder6Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder7Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder8Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder9Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder10Value4, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11Value0, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11Value1, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11Value2, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11Value3, computedPhasedBaseFullFiveInnerThreeDirectGroup21BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10,
  computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11
]

def computedPhasedBaseFullFiveInnerThreeDirectGroup21Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerThreeCompactCell3Shard8Interval.center where
  base := computedPhasedBaseFullFiveInnerThreeDirectGroup21Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerThreeDirectGroup21BaseOrder11_contains

end
end RiemannVenue.Venue
