import RiemannVenue.Venue.BoundaryComputedPhasedBaseFullFiveInnerTwoDirectGroup22GroupCache

/-! Direct three-block base-jet cache. -/
namespace RiemannVenue.Venue
noncomputable section
set_option maxHeartbeats 3000000

def computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed (n : Fin 12) (b : Fin 5) : RationalInterval :=
  RationalInterval.finSum fun g : Fin 4 => computedPhasedBaseFullFiveInnerTwoDirectGroup22Group n b g

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed_contains (n : Fin 12) (b : Fin 5) :
    (computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed n b).Contains
      (∑ g : Fin 20, computedPhasedBaseCoefficient (computedPhasedBaseFullFiveModel.column b g) *
        computedPhasedCosineJet n (computedPhasedBaseFullFiveModel.column b g)
          (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  rw [computedPhasedBaseActiveBlock_signedCosine_eq_groups]
  exact RationalInterval.contains_finSum fun g => computedPhasedBaseFullFiveInnerTwoDirectGroup22Group_contains n b g

def computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache : ComputedPhasedBaseActiveBlockPointSignedCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval where
  signed := computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed
  signed_contains := by
    intro n b x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed_contains n b

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache : ComputedPhasedBaseActiveBlockPointBumpCache
    computedPhasedBaseFullFiveModel computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval where
  bump := computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump
  bump_contains := by
    intro b n x hx
    have hx' : x = (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ) := by
      have hz : x - (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ) = 0 := by
        simpa [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
          RationalInterval.singleton, RationalInterval.Contains] using hx
      linarith
    subst x
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump_contains b n

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (0 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0 : RationalInterval :=
  ⟨(-104687163641880159 : ℚ) / 2000000000000000000, (832283 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0Raw.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (0 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0.Contains
    (computedPhasedBaseTest.iterDeriv 0
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (1 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1 : RationalInterval :=
  ⟨(-536514425679332481 : ℚ) / 400000000000000000, (35415181 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1Raw.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (1 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1.Contains
    (computedPhasedBaseTest.iterDeriv 1
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (2 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2 : RationalInterval :=
  ⟨(-536381638607800627 : ℚ) / 100000000000000000, (754255417 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2Raw.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (2 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2.Contains
    (computedPhasedBaseTest.iterDeriv 2
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (3 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3 : RationalInterval :=
  ⟨(31451456013994703537 : ℚ) / 80000000000000000, (64292036303 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3Raw.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (3 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3.Contains
    (computedPhasedBaseTest.iterDeriv 3
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (4 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4 : RationalInterval :=
  ⟨(-577800883660414511401 : ℚ) / 100000000000000000, (1370547820143 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4Raw.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (4 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4.Contains
    (computedPhasedBaseTest.iterDeriv 4
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (5 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5 : RationalInterval :=
  ⟨(-156713868388324760443211 : ℚ) / 250000000000000000, (2922517027623 : ℚ) / 50000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5Raw.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (5 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5.Contains
    (computedPhasedBaseTest.iterDeriv 5
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (6 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6 : RationalInterval :=
  ⟨(5788074205472232732329661 : ℚ) / 500000000000000000, (2493345210497241 : ℚ) / 1000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6Raw.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (6 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6.Contains
    (computedPhasedBaseTest.iterDeriv 6
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (7 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7 : RationalInterval :=
  ⟨(686122417026596316019322303 : ℚ) / 500000000000000000, (21276618563435659 : ℚ) / 200000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7Raw.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (7 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7.Contains
    (computedPhasedBaseTest.iterDeriv 7
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder7,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (8 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8 : RationalInterval :=
  ⟨(-18042323149723932708094148649 : ℚ) / 2000000000000000000, (9079831518274533219 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8Raw.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (8 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8.Contains
    (computedPhasedBaseTest.iterDeriv 8
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder8,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (9 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9 : RationalInterval :=
  ⟨(-1094812293401656807795481502743 : ℚ) / 400000000000000000, (77511427135423565151 : ℚ) / 400000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9Raw.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (9 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9.Contains
    (computedPhasedBaseTest.iterDeriv 9
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder9,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (10 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10 : RationalInterval :=
  ⟨(-17859977896968943144381732141769 : ℚ) / 2000000000000000000, (16545158504332834080671 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10Raw.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (10 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10.Contains
    (computedPhasedBaseTest.iterDeriv 10
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder10,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11Raw : RationalInterval :=
  computedPhasedBaseActiveBlockTestJetFromPointCaches
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (11 : Fin 12)

def computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11 : RationalInterval :=
  ⟨(10309249205671474541765003751045377 : ℚ) / 2000000000000000000, (706452882023057817589113 : ℚ) / 2000000000000000000⟩

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11Raw_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11Raw.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  exact computedPhasedBaseActiveBlockTestJetFromPointCaches_contains
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache (11 : Fin 12)
    (by simp [computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11PointInterval, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval,
      RationalInterval.singleton, RationalInterval.Contains])
    (by norm_num [computedPhasedBaseFullFiveModel, computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval])

theorem computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11_contains : computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11.Contains
    (computedPhasedBaseTest.iterDeriv 11
      (computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center : ℝ)) := by
  apply RationalInterval.contains_of_center_radius_le computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11Raw_contains
  simp [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11Raw, computedPhasedBaseActiveBlockTestJetFromPointCaches,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22SignedCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Signed, computedPhasedBaseFullFiveInnerTwoDirectGroup22Group, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup22GroupOrder11,
    computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpCache, computedPhasedBaseFullFiveInnerTwoDirectGroup22Bump, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11,
    RationalInterval.finSum]
  norm_num (config := { maxSteps := 1000000 })
    [computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder0Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder1Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder2Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder3Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder4Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder5Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder6Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder7Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder8Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder9Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder10Value4, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11Value0, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11Value1, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11Value2, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11Value3, computedPhasedBaseFullFiveInnerTwoDirectGroup22BumpOrder11Value4, RationalInterval.finSum,
      RationalInterval.scale, RationalInterval.mul, RationalInterval.add,
      RationalInterval.neg, RationalInterval.zero,
      RationalInterval.singleton, Nat.choose]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22Base : Fin 12 → RationalInterval := ![
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10,
  computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11
]

def computedPhasedBaseFullFiveInnerTwoDirectGroup22Jets : ComputedPhasedBaseOuterMidpointJets
    computedPhasedBaseFullFiveInnerTwoCompactCell3Shard11Interval.center where
  base := computedPhasedBaseFullFiveInnerTwoDirectGroup22Base
  base_contains := by
    intro n
    fin_cases n
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder0_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder1_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder2_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder3_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder4_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder5_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder6_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder7_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder8_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder9_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder10_contains
    exact computedPhasedBaseFullFiveInnerTwoDirectGroup22BaseOrder11_contains

end
end RiemannVenue.Venue
