import RiemannVenue.Venue.BoundaryComputedPhasedBumpQuadratureTable

/-! Kernel-checked bump quadrature leaves for jet 1, block 13. Generated by `scripts/generate_computed_phased_bump_quadrature.py`. -/
namespace RiemannVenue.Venue
noncomputable section

set_option maxRecDepth 100000

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_208 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨208, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨208, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨208, by norm_num⟩)).absUpper ≤
      (8785223/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_209 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨209, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨209, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨209, by norm_num⟩)).absUpper ≤
      (2183587/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_210 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨210, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨210, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨210, by norm_num⟩)).absUpper ≤
      (8670433/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_211 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨211, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨211, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨211, by norm_num⟩)).absUpper ≤
      (2148181/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_212 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨212, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨212, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨212, by norm_num⟩)).absUpper ≤
      (531279/62500 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_213 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨213, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨213, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨213, by norm_num⟩)).absUpper ≤
      (4196451/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_214 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨214, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨214, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨214, by norm_num⟩)).absUpper ≤
      (1653861/200000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_215 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨215, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨215, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨215, by norm_num⟩)).absUpper ≤
      (8128963/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_216 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨216, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨216, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨216, by norm_num⟩)).absUpper ≤
      (1992803/250000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_217 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨217, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨217, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨217, by norm_num⟩)).absUpper ≤
      (7795443/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_218 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨218, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨218, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨218, by norm_num⟩)).absUpper ≤
      (60809/8000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_219 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨219, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨219, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨219, by norm_num⟩)).absUpper ≤
      (295513/40000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_220 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨220, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨220, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨220, by norm_num⟩)).absUpper ≤
      (7155237/1000000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_221 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨221, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨221, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨221, by norm_num⟩)).absUpper ≤
      (3451603/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_222 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨222, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨222, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨222, by norm_num⟩)).absUpper ≤
      (3315883/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]

set_option maxHeartbeats 2000000 in
theorem computedPhasedBumpRawUpper_le_certified_1_223 :
    (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2
      1 (computedPhasedBumpQuadratureCell ⟨223, by norm_num⟩)).absUpper ≤
        computedPhasedBumpCertifiedUpperQ ⟨1, by norm_num⟩ ⟨223, by norm_num⟩ := by
  change (explicitBumpPositiveWeightedJetCellInterval 32 16 24 2 1
    (computedPhasedBumpQuadratureCell ⟨223, by norm_num⟩)).absUpper ≤
      (3170587/500000 : ℚ)
  norm_num [RationalInterval.absUpper, computedPhasedBumpQuadratureCell,
      explicitBumpPositiveWeightedJetCellInterval,
      explicitStandardBumpJetCellInterval,
      explicitBumpBoundaryJetPolynomialInterval,
      explicitBumpBoundaryJetCoefficients, explicitBumpBoundaryYInterval,
      explicitBumpGapInterval, monotoneExpInterval,
      RationalInterval.reciprocalPositive, RationalInterval.ofBounds,
      rangeReducedExpInterval, rationalExpInterval, rationalExpTaylor,
      rationalExpRemainder, RationalInterval.evalPolynomial,
      RationalInterval.lower, RationalInterval.upper, RationalInterval.mul,
      RationalInterval.add, RationalInterval.sub, RationalInterval.neg,
      RationalInterval.pow, RationalInterval.singleton, RationalInterval.one,
      RationalInterval.zero, Finset.sum_range_succ]


end
end RiemannVenue.Venue
