import RiemannVenue.Venue.BoundaryComputedPhasedTransformBumpJets6To8

/-!
# Sparse bump-jet numerators 9 through 11

Generated by `scripts/generate_computed_phased_transform_bump_jets.py`.
Every polynomial is checked from the defining recurrence; these are
matrix-transform proof shards, not numerical authority.
-/

namespace RiemannVenue.Venue

open Polynomial

noncomputable def computedTransformBumpJetNumerator9 : ℤ[X] :=
  (574560 : ℤ[X]) * X ^ 1 +
      (6975360 : ℤ[X]) * X ^ 3 +
      ((-48940416) : ℤ[X]) * X ^ 5 +
      (24072192 : ℤ[X]) * X ^ 7 +
      (374038336 : ℤ[X]) * X ^ 9 +
      ((-926210304) : ℤ[X]) * X ^ 11 +
      (611130240 : ℤ[X]) * X ^ 13 +
      (524966400 : ℤ[X]) * X ^ 15 +
      ((-941461920) : ℤ[X]) * X ^ 17 +
      (346792320 : ℤ[X]) * X ^ 19 +
      (82494720 : ℤ[X]) * X ^ 21 +
      ((-50803200) : ℤ[X]) * X ^ 23 +
      ((-3628800) : ℤ[X]) * X ^ 25

theorem explicitStandardBumpJetNumerator_eq_9 :
    explicitStandardBumpJetNumerator 9 =
      computedTransformBumpJetNumerator9 := by
  rw [show 9 = 8 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_8]
  simp [
    computedTransformBumpJetNumerator8,
    computedTransformBumpJetNumerator9,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

noncomputable def computedTransformBumpJetNumerator10 : ℤ[X] :=
  (574560 : ℤ[X]) +
      (39312000 : ℤ[X]) * X ^ 2 +
      ((-69501600) : ℤ[X]) * X ^ 4 +
      ((-1236251520) : ℤ[X]) * X ^ 6 +
      (5364941760 : ℤ[X]) * X ^ 8 +
      ((-4901793536) : ℤ[X]) * X ^ 10 +
      ((-13268865600) : ℤ[X]) * X ^ 12 +
      (35918795520 : ℤ[X]) * X ^ 14 +
      ((-27960982560) : ℤ[X]) * X ^ 16 +
      ((-4435240320) : ℤ[X]) * X ^ 18 +
      (18232996320 : ℤ[X]) * X ^ 20 +
      ((-7723900800) : ℤ[X]) * X ^ 22 +
      ((-718502400) : ℤ[X]) * X ^ 24 +
      (718502400 : ℤ[X]) * X ^ 26 +
      (39916800 : ℤ[X]) * X ^ 28

theorem explicitStandardBumpJetNumerator_eq_10 :
    explicitStandardBumpJetNumerator 10 =
      computedTransformBumpJetNumerator10 := by
  rw [show 10 = 9 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_9]
  simp [
    computedTransformBumpJetNumerator9,
    computedTransformBumpJetNumerator10,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

noncomputable def computedTransformBumpJetNumerator11 : ℤ[X] :=
  (100457280 : ℤ[X]) * X ^ 1 +
      (1035619200 : ℤ[X]) * X ^ 3 +
      ((-10996413120) : ℤ[X]) * X ^ 5 +
      (13279052160 : ℤ[X]) * X ^ 7 +
      (111043335040 : ℤ[X]) * X ^ 9 +
      ((-419136807168) : ℤ[X]) * X ^ 11 +
      (464152824960 : ℤ[X]) * X ^ 13 +
      (283340471040 : ℤ[X]) * X ^ 15 +
      ((-1181488904640) : ℤ[X]) * X ^ 17 +
      (1026853027200 : ℤ[X]) * X ^ 19 +
      ((-108816523200) : ℤ[X]) * X ^ 21 +
      ((-335560579200) : ℤ[X]) * X ^ 23 +
      (164896300800 : ℤ[X]) * X ^ 25 +
      (2554675200 : ℤ[X]) * X ^ 27 +
      ((-10777536000) : ℤ[X]) * X ^ 29 +
      ((-479001600) : ℤ[X]) * X ^ 31

theorem explicitStandardBumpJetNumerator_eq_11 :
    explicitStandardBumpJetNumerator 11 =
      computedTransformBumpJetNumerator11 := by
  rw [show 11 = 10 + 1 by norm_num,
    explicitStandardBumpJetNumerator_succ,
    explicitStandardBumpJetNumerator_eq_10]
  simp [
    computedTransformBumpJetNumerator10,
    computedTransformBumpJetNumerator11,
    Polynomial.derivative_add, Polynomial.derivative_mul,
    Polynomial.derivative_C, Polynomial.derivative_X_pow,
    Polynomial.derivative_one, Polynomial.derivative_natCast,
    Polynomial.derivative_intCast]
  all_goals ring

end RiemannVenue.Venue
